
# https://github.com/Huachao/vscode-restclient

# @baseURL = http://localhost:4000

@baseURL = https://api.philipdick.com

GET {{baseURL}}/categories

###

GET {{baseURL}}/media

###

GET {{baseURL}}/titles

###

GET {{baseURL}}/titles/broken/1

###

GET {{baseURL}}/editions

###

GET {{baseURL}}/editions/broken/1

###

GET {{baseURL}}/userreviews

###

GET {{baseURL}}/terms

###

GET {{baseURL}}/terms/2

###

GET {{baseURL}}/logs

###

GET {{baseURL}}/errors

###

GET {{baseURL}}/computerLogs

###

GET {{baseURL}}/computerLogs/broken

###

GET {{baseURL}}/fromthehomeopape

###

GET {{baseURL}}/fromthehomeopape/review

###

GET {{baseURL}}/fromthehomeopape/markviewed

###

# Runs the import of new data from the RSS feeds. -- 11/14/2021 MF
GET {{baseURL}}/fromthehomeopape/new

###

# Runs the inserting of new data from the import. -- 11/14/2021 MF
GET {{baseURL}}/fromthehomeopape/insert

###

# Runs the updating of new data from the import. -- 12/26/2021 MF
GET {{baseURL}}/fromthehomeopape/update

###

GET {{baseURL}}/amazon/authorPhilipKDick/AvgCustomerReviews

###

GET {{baseURL}}/amazon/authorPhilipKDick/Featured

###

GET {{baseURL}}/amazon/authorPhilipKDick/NewestArrivals

###

GET {{baseURL}}/amazon/authorPhilipKDick/PriceHighToLow

###

GET {{baseURL}}/amazon/authorPhilipKDick/PriceLowToHigh

###

GET {{baseURL}}/amazon/authorPhilipKDick/Relevance

###

GET {{baseURL}}/amazon/keywordsPhilipDick/Books/AvgCustomerReviews

###

GET {{baseURL}}/amazon/keywordsPhilipDick/Books/Featured

###

GET {{baseURL}}/amazon/keywordsPhilipDick/Books/NewestArrivals

###

GET {{baseURL}}/amazon/keywordsPhilipDick/Books/PriceHighToLow

###

GET {{baseURL}}/amazon/keywordsPhilipDick/Books/PriceLowToHigh

###

GET {{baseURL}}/amazon/keywordsPhilipDick/Books/Relevance

###

GET {{baseURL}}/amazon/keywordsBladeRunner/Books/AvgCustomerReviews

###

GET {{baseURL}}/amazon/keywordsBladeRunner/Books/Featured

###

GET {{baseURL}}/amazon/keywordsBladeRunner/Books/NewestArrivals

###

GET {{baseURL}}/amazon/keywordsBladeRunner/Books/PriceHighToLow

###

GET {{baseURL}}/amazon/keywordsBladeRunner/Books/PriceLowToHigh

###

GET {{baseURL}}/amazon/keywordsBladeRunner/Books/Relevance

###

GET {{baseURL}}/test/

###

GET {{baseURL}}/test/addline

###


https://www.google.com/alerts/feeds/17849810695950872924/15842463258895766468

###

https://www.google.com/alerts/feeds/17849810695950872924/2465476321108416249

###

https://www.google.com/alerts/feeds/17849810695950872924/11918400074382766835

###

https://www.google.com/alerts/feeds/17849810695950872924/17162147117770349674

###

https://www.google.com/alerts/feeds/17849810695950872924/2707042161623420058

###

