
# https://github.com/Huachao/vscode-restclient

# @baseURL = http://localhost:4000

@baseURL = https://api.philipdick.com

GET {{baseURL}}/categories

###

GET {{baseURL}}/media

###

GET {{baseURL}}/titles

###

GET {{baseURL}}/editions

###

GET {{baseURL}}/userreviews

###

GET {{baseURL}}/fromthehomeopape

###
