
# https://github.com/Huachao/vscode-restclient

# @baseURL = http://localhost:4000

@baseURL = https://api.philipdick.com

GET {{baseURL}}/categories

###

GET {{baseURL}}/media

###

GET {{baseURL}}/titles

###

GET {{baseURL}}/titles/broken/1

###

GET {{baseURL}}/editions

###

GET {{baseURL}}/editions/broken/1

###

GET {{baseURL}}/userreviews

###

GET {{baseURL}}/computerLogs

###

GET {{baseURL}}/computerLogs/broken

###

GET {{baseURL}}/fromthehomeopape

###

GET {{baseURL}}/fromthehomeopape/review

###

GET {{baseURL}}/fromthehomeopape/markviewed

###

# Runs the import of new data from the RSS feeds. -- 11/14/2021 MF
GET {{baseURL}}/fromthehomeopape/new

###

# Runs the inserting of new data from the import. -- 11/14/2021 MF
GET {{baseURL}}/fromthehomeopape/update

###

https://www.google.com/alerts/feeds/17849810695950872924/15842463258895766468

###

https://www.google.com/alerts/feeds/17849810695950872924/2465476321108416249

###

https://www.google.com/alerts/feeds/17849810695950872924/11918400074382766835

###

https://www.google.com/alerts/feeds/17849810695950872924/17162147117770349674

###

https://www.google.com/alerts/feeds/17849810695950872924/2707042161623420058

###

