
DROP TABLE IF EXISTS `userReviews`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `editions`;
DROP TABLE IF EXISTS `titles`;
DROP TABLE IF EXISTS `categories`;
DROP TABLE IF EXISTS `media`;
