
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('GATHER YOURSELVES TOGETHER','May 1952','1994', 16)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('VOICES FROM THE STREET','June 1952','Jan 2007', 41)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('SOLAR LOTTERY','Mar 23, 1954','May 1955', 34)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE WORLD JONES MADE','Dec 28, 1954','Mar 1956', 44)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('EYE IN THE SKY','Feb 15, 1955','1957', 12)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('MARY AND THE GIANT','','Apr 1987', 24)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE MAN WHO JAPED','Oct 17, 1955','Dec 1956', 21)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE BROKEN BUBBLE','Nov 13, 1956','Jul 1988', 1)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE COSMIC PUPPETS','May 1, 1957','Oct 1957', 4)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('PUTTERING ABOUT IN A SMALL LAND','May 15, 1957','Oct 1985', 30 )
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('TIME OUT OF JOINT','Apr 7, 1958','1959', 36)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('IN MILTON LUMKY TERRITORY','Oct 8, 1958','Jun 1985', 18)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('DR. FUTURITY','Jul 28, 1959','Feb 1960', 11)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('CONFESSIONS OF A CRAP ARTIST','','1975', 3)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('VULCAN S HAMMER','Feb 16, 1960','Sep 1960', 42)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE MAN WHOSE TEETH WERE ALL EXAC','','Jun 1984', 22)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('HUMPTY DUMPTY IN OAKLAND','Oct/Nov 1960','1986', 17)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE MAN IN THE HIGH CASTLE','Nov 29, 1961','Oct 1962', 20)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('WE CAN BUILD YOU','Oct 4, 1962','Jul 1972', 43)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('MARTIAN TIME-SLIP','Oct 31, 1962','Apr 1964', 23)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('DR. BLOODMONEY','Feb 11, 1963','Jun 1965', 10)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE GAME-PLAYERS OF TITAN','Jun 4, 1963','Dec 1963', 15)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE SIMULACRA','Aug 28, 1963','Aug 1964', 33)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('NOW WAIT FOR LAST YEAR','Dec 4, 1963','May 1966', 27)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('CLANS OF THE ALPHANE MOON','Jan 16, 1964','Nov 1964', 2)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE CRACK IN SPACE','Mar 17, 1964','Feb 1966', 6)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE THREE STIGMATA OF PALMER ELD','Mar 18, 1964','Nov 1964', 35)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE ZAP GUN','Apr 15, 1964','Jan 1967', 45)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE PENULTIMATE TRUTH','May 12, 1964','Sep 1964', 29)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('LIES, INC.','May 5, 1965','July 1984', 19)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('COUNTER-CLOCK WORLD','','Feb 1967', 5)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE GANYMEDE TAKEOVER','','Jun 1967', 186)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('DO ANDROIDS DREAM OF ELECTRIC SH','Jun 20, 1966','Mar 1968', 9)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('UBIK','Dec 7, 1966','May 1969', 38)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('NICK AND THE GLIMMUNG','Dec 7, 1966','Jun 1988', 26)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('GALACTIC POT-HEALER','','Jun 1969', 14)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('A MAZE OF DEATH','Oct 31, 1968','Jul 1970', 25)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('OUR FRIENDS FROM FROLIX 8','Jul 2, 1969','Jun 1970', 28)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('FLOW MY TEARS, THE POLICEMAN SAI','Feb 7, 1973','Feb 1974', 13)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('A SCANNER DARKLY','Aug 29, 1975','Jan 1977', 32)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('UBIK: THE SCREENPLAY','','Aug 1985', 39)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('DEUS IRAE','Aug 17, 1975','Jul 1976', 7)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('RADIO FREE ALBEMUTH','Aug 19, 1976','Dec 1985', 31)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('VALIS','Dec 7, 1978','Feb 1981', 40)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE DIVINE INVASION','Mar 14, 1980','Jun 1981', 8)
INSERT INTO titlesCheck (titleName, submissionDate, publicationDate, titleID) VALUES ('THE TRANSMIGRATION OF TIMOTHY AR','May 13, 1981','Apr 1982', 37)