
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Broken Bubble', 'titleSort', 'Philip K.', 'Dick', '01/01/1988', 'TheBrokenBubble.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Clans of the Alphane Moon', 'titleSort', 'Philip K.', 'Dick', '01/01/1964', 'ClansOfTheAlphaneMoon.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Confessions of a Crap Artist', 'titleSort', 'Philip K.', 'Dick', '01/01/1975', 'ConfessionsOfACrapArtist.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Cosmic Puppets', 'titleSort', 'Philip K.', 'Dick', '01/01/1957', 'TheCosmicPuppets.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Counter-Clock World', 'titleSort', 'Philip K.', 'Dick', '01/01/1967', 'CounterClockWorld.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Crack in Space', 'titleSort', 'Philip K.', 'Dick', '01/01/1966', 'TheCrackInSpace.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Deus Irae', 'titleSort', 'Philip K.', 'Dick', '01/01/1976', 'DeusIrae.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Divine Invasion', 'titleSort', 'Philip K.', 'Dick', '01/01/1981', 'TheDivineInvasion.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Do Androids Dream of Electric Sheep?', 'titleSort', 'Philip K.', 'Dick', '01/01/1968', 'DoAndroidsDreamOfElectricSheep.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Dr. Bloodmoney', 'titleSort', 'Philip K.', 'Dick', '01/01/1965', 'DrBloodmoney.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Dr. Futurity', 'titleSort', 'Philip K.', 'Dick', '01/01/1960', 'DrFuturity.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Eye in the Sky', 'titleSort', 'Philip K.', 'Dick', '01/01/1957', 'EyeInTheSky.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Flow My Tears, the Policeman Said', 'titleSort', 'Philip K.', 'Dick', '01/01/1974', 'FlowMyTearsThePolicemanSaid.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Galactic Pot-Healer', 'titleSort', 'Philip K.', 'Dick', '01/01/1969', 'GalacticPotHealer.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Game-Players of Titan', 'titleSort', 'Philip K.', 'Dick', '01/01/1963', 'TheGamePlayersOfTitan.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Gather Yourselves Together', 'titleSort', 'Philip K.', 'Dick', '01/01/1994', 'GatherYourselvesTogether.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Humpty Dumpty in Oakland', 'titleSort', 'Philip K.', 'Dick', '01/01/1986', 'HumptyDumptyInOakland.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('In Milton Lumky Territory', 'titleSort', 'Philip K.', 'Dick', '01/01/1985', 'InMiltonLumkyTerritory.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Lies, Inc.', 'titleSort', 'Philip K.', 'Dick', '01/01/1984', 'LiesInc.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Man in the High Castle', 'titleSort', 'Philip K.', 'Dick', '01/01/1962', 'TheManInTheHighCastle.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Man Who Japed', 'titleSort', 'Philip K.', 'Dick', '01/01/1956', 'TheManWhoJaped.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Man Whose Teeth Were All Exactly Alike', 'titleSort', 'Philip K.', 'Dick', '01/01/1984', 'TheManWhoseTeethWereAllExactlyAlike.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Martian Time-Slip', 'titleSort', 'Philip K.', 'Dick', '01/01/1964', 'MartianTimeSlip.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Mary and the Giant', 'titleSort', 'Philip K.', 'Dick', '01/01/1987', 'MaryAndTheGiant.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('A Maze of Death', 'titleSort', 'Philip K.', 'Dick', '01/01/1970', 'AMazeOfDeath.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Nick and the Glimmung', 'titleSort', 'Philip K.', 'Dick', '01/01/1988', 'NickAndTheGlimmung.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Now Wait for Last Year', 'titleSort', 'Philip K.', 'Dick', '01/01/1966', 'NowWaitForLastYear.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Our Friends from Frolix 8', 'titleSort', 'Philip K.', 'Dick', '01/01/1970', 'OurFriendsFromFrolix8.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Penultimate Truth', 'titleSort', 'Philip K.', 'Dick', '01/01/1964', 'ThePenultimateTruth.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Puttering About in a Small Land', 'titleSort', 'Philip K.', 'Dick', '01/01/1985', 'PutteringAboutInASmallLand.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Radio Free Albemuth', 'titleSort', 'Philip K.', 'Dick', '01/01/1985', 'RadioFreeAlbemuth.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('A Scanner Darkly', 'titleSort', 'Philip K.', 'Dick', '01/01/1977', 'AScannerDarkly.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Simulacra', 'titleSort', 'Philip K.', 'Dick', '01/01/1964', 'TheSimulacra.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Solar Lottery', 'titleSort', 'Philip K.', 'Dick', '01/01/1955', 'SolarLottery.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Three Stigmata of Palmer Eldritch', 'titleSort', 'Philip K.', 'Dick', '01/01/1965', 'TheThreeStigmataOfPalmerEldritch.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Time Out of Joint', 'titleSort', 'Philip K.', 'Dick', '01/01/1959', 'TimeOutOfJoint.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Transmigration of Timothy Archer', 'titleSort', 'Philip K.', 'Dick', '01/01/1982', 'TheTransmigrationOfTimothyArcher.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Ubik', 'titleSort', 'Philip K.', 'Dick', '01/01/1969', 'Ubik.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Ubik: The Screenplay', 'titleSort', 'Philip K.', 'Dick', '01/01/1985', 'UbikTheScreenplay.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('VALIS', 'titleSort', 'Philip K.', 'Dick', '01/01/1981', 'VALIS.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Voices From the Street', 'titleSort', 'Philip K.', 'Dick', '01/01/2007', 'VoicesFromTheStreet.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Vulcan''s Hammer', 'titleSort', 'Philip K.', 'Dick', '01/01/1960', 'VulcansHammer.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('We Can Build You', 'titleSort', 'Philip K.', 'Dick', '01/01/1972', 'WeCanBuildYou.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The World Jones Made', 'titleSort', 'Philip K.', 'Dick', '01/01/1956', 'TheWorldJonesMade.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Zap Gun', 'titleSort', 'Philip K.', 'Dick', '01/01/1967', 'TheZapGun.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The VALIS Trilogy', 'titleSort', 'Philip K.', 'Dick', '01/01/1982', 'TheVALISTrilogy.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
--INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Blade Runner', 'titleSort', 'Philip K.', 'Dick', '01/01/1968', 'BladeRunner.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Novels'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Total Recall', 'titleSort', 'Philip K.', 'Dick', null, 'TotalRecall.jpg', (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());



INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Minority Report and Other Stories', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Unreconstructed M and Other Stories', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Volume I: The King of the Elves (The Collected Stories of Philip K. Dick)', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Volume II: Adjustment Team (The Collected Stories of Philip K. Dick)', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Volume III: Upon the Dull Earth (The Collected Stories of Philip K. Dick)', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Volume IV: The Minority Report (The Collected Stories of Philip K. Dick)', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Volume V: We Can Remember It for You Wholesale (The Collected Stories of Philip K. Dick)', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Philip K. Dick''s Electric Dreams', 'titleSort', 'Philip K.', 'Dick', '11/14/2017', null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Early Work of Philip K. Dick, Volume 1: The Variable Man and Other Stories', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Early Work of Philip K. Dick, Volume 2: Breakfast at Twilight and Other Stories', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Philip K. Dick Reader', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Selected Stories of Philip K. Dick', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('Vintage PKD', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Best of Philip K. Dick', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Collected Short Stories of Philip K. Dick, Vol. 1', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Collected Short Stories of Philip K. Dick, Vol. 2', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Collected Short Stories of Philip K. Dick, Vol. 3', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Collected Short Stories of Philip K. Dick, Vol. 4', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Collected Short Stories of Philip K. Dick, Vol. 5', 'titleSort', 'Philip K.', 'Dick', null, null, (SELECT "categoryID" FROM categories WHERE category = 'Short Stories'), '', '', NOW(), NOW());



INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('X Minus One: Colony', 'titleSort', 'Philip K.', 'Dick', '10/10/1956', null, (SELECT "categoryID" FROM categories WHERE category = 'Radio'), '', '', NOW(), NOW());
INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('X Minus One: The Defenders', 'titleSort', 'Philip K.', 'Dick', '05/22/1956', null, (SELECT "categoryID" FROM categories WHERE category = 'Radio'), '', '', NOW(), NOW());



INSERT INTO titles ("titleName", "titleSort", "authorFirstName", "authorLastName", "publicationDate", "imageName", "categoryID", "shortDescription", "urlPKDweb", "createdAt", "updatedAt") values ('The Exegesis of Philip K. Dick', 'titleSort', 'Philip K.', 'Dick', '11/08/2011', null, (SELECT "categoryID" FROM categories WHERE category = 'Non Fiction'), '', '', NOW(), NOW());









UPDATE titles SET "titleSort" = regexp_replace(lower("titleName"), '^(an?|the) (.*)$', '\2, \1');


